In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

**Import libiraries:**

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler

**Load Dataset**

In [ ]:
file_path = "/content/drive/MyDrive/355227_6a050b3f72794_1778715455.xlsx"

df = pd.read_excel(file_path)

In [ ]:
print("First 5 Rows:")
display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nDataset Info:")
print(df.info())

print("\nMissing Values:")
print(df.isnull().sum())

First 5 Rows:

  Customer_ID   Age  Gender  Monthly_Bill  Total_Spend  Churn
0       C2016  70.0    male         32.66       195.96      1
1       C2307  41.0  Female         26.90       322.80      1
2       C3521  49.0    Male        131.85      2373.30      0
3       C1122  41.0  Female        202.26      4247.46      1
4       C2668  53.0    Male         33.40       233.80      1

Dataset Shape:
(3000, 6)

Dataset Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Customer_ID   3000 non-null   object
 1   Age           2849 non-null   float64
 2   Gender        3000 non-null   object
 3   Monthly_Bill  3000 non-null   float64
 4   Total_Spend   2716 non-null   float64
 5   Churn         3000 non-null   int64
dtypes: float64(3), int64(1), object(2)
memory usage: 140.8+ KB
None

Missing Values:
Customer_ID       0
Age             151
Gender            0
Monthly_Bill      0
Total_Spend     284
Churn             0
dtype: int64

**Remove duplicate**

In [ ]:
duplicates_removed = df.duplicated().sum()

df = df.drop_duplicates()

print("\nDuplicates Removed:", duplicates_removed)

Duplicates Removed: 0

**Handle Missing Values**

In [ ]:
missing_before = df.isnull().sum().sum()

for col in df.columns:


    if df[col].dtype == 'object':

        mode_value = df[col].mode()[0]

        df[col] = df[col].fillna(mode_value)


    else:

        median_value = df[col].median()

        df[col] = df[col].fillna(median_value)

missing_after = df.isnull().sum().sum()

print("\nMissing Values Before:", missing_before)
print("Missing Values After:", missing_after)

Missing Values Before: 435
Missing Values After: 0

**HANDLE OUTLIERS**

In [ ]:
age_col = "Age"

Q1 = df[age_col].quantile(0.25)
Q3 = df[age_col].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

before_outliers = len(df)

df = df[
    (df[age_col] >= lower_bound) &
    (df[age_col] <= upper_bound)
]

after_outliers = len(df)

outliers_removed = before_outliers - after_outliers

print("\nOutliers Removed:", outliers_removed)

Outliers Removed: 80

**FEATURE ENGINEERING**

In [ ]:
text_columns = df.select_dtypes(include=['object']).columns

for col in text_columns:

    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

print("\nText Standardization Completed")

Text Standardization Completed

In [ ]:
# Encoding Categorical Data

label_encoders = {}

for col in text_columns:

    encoder = LabelEncoder()

    df[col] = encoder.fit_transform(df[col])

    label_encoders[col] = encoder

print("Encoding Completed")

Encoding Completed

In [ ]:
#SCALING
billing_col = "Monthly_Bill"

scaler = MinMaxScaler()

df[[billing_col]] = scaler.fit_transform(df[[billing_col]])

print("\nScaling Completed")

Scaling Completed

In [ ]:
print("\nFinal Dataset Shape:")
print(df.shape)

print("\nFirst 5 Rows After Cleaning:")
display(df.head())

Final Dataset Shape:
(2920, 6)

First 5 Rows After Cleaning:

   Customer_ID   Age  Gender  Monthly_Bill  Total_Spend  Churn
0          980  70.0       2      0.026229       195.96      1
1         1266  41.0       1      0.014220       322.80      1
2         2454  49.0       2      0.233039      2373.30      0
3          118  41.0       1      0.379842      4247.46      1
4         1623  53.0       2      0.027772       233.80      1

In [ ]:
output_path = "/content/drive/MyDrive/cleaned_telecom_dataset.xlsx"

df.to_excel(output_path, index=False)

print("\nCleaned Dataset Saved Successfully")

Cleaned Dataset Saved Successfully

In [ ]:

print("\n================ REPORT ================")

print(f"""
1. Removed Duplicates:
   - {duplicates_removed} duplicate rows removed.

2. Missing Values:
   - Missing values before cleaning: {missing_before}
   - Missing values after cleaning: {missing_after}

3. Outliers:
   - Removed {outliers_removed} outliers from Age column using IQR method.

4. Feature Engineering:
   - Standardized text columns.
   - Applied Label Encoding on categorical columns.

5. Scaling:
   - Applied MinMax Scaling on MonthlyCharges column.

6. Final Dataset Shape:
   - {df.shape}
""")

================ REPORT ================

1. Removed Duplicates:
   - 0 duplicate rows removed.

2. Missing Values:
   - Missing values before cleaning: 435
   - Missing values after cleaning: 0

3. Outliers:
   - Removed 80 outliers from Age column using IQR method.

4. Feature Engineering:
   - Standardized text columns.
   - Applied Label Encoding on categorical columns.

5. Scaling:
   - Applied MinMax Scaling on MonthlyCharges column.

6. Final Dataset Shape:
   - (2920, 6)